Location cant be blank
berkmancenter/bookanook pull request #188
Opened 2017-01-09 03:31 UTC by kctrlv

Hi @shubhpatel108

I believe this is what the issue wanted to accomplish. The admin can no longer create a location without a name. A note about the admin/locations_controller change: 

Lines 71 through 73 were added because the resource would not have an `OpenSchedule` otherwise. Without it, there would be a failure down the stack in the `OpenAtField#days` method where `data` would be nil. 

Otherwise this was a simple fix to add a validation to the model and flash the alert when the resource fails to be saved, adding a spec, and updating a former spec to now include a name.

I believe this meets the indented functionality, please look it over and let me know. 
Best, David

Closes #130

2017-01-09 15:19 UTC, jcasimir commented
Looks good to me! 👍

2017-03-17 08:26 UTC, shubhpatel108 requested changes
Over all seems go to me. Adding comment regarding localisation. 
Thanks @kctrlv for this contribution!!

2017-03-17 08:26 UTC, shubhpatel108 commented on spec/models/location_spec.rb
> +      expect(location.errors.full_messages).to include("Name can't be blank")
This assertion will fail if the user locale is not EN. Use this message from respective yml files (e.g. en.yml). I believe we don't have a sample code to demonstrate this in test though.

2017-03-17 08:50 UTC, shubhpatel108 approved these changes

2017-03-17 08:51 UTC, shubhpatel108 commented on spec/models/location_spec.rb
> +      expect(location.errors.full_messages).to include("Name can't be blank")
Just noticed that even in the controller the messages are hard coded. Approving!

2017-03-22 16:34 UTC, merged